# Generated by Django 4.1.2 on 2022-10-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0002_pertanyaandanjawabanmodels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaandanjawabanmodels',
            name='jawaban',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pertanyaandanjawabanmodels',
            name='penanya',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pertanyaandanjawabanmodels',
            name='penjawab',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pertanyaandanjawabanmodels',
            name='pertanyaan',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
