# Generated by Django 4.1.2 on 2022-10-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0004_alter_pertanyaandanjawabanmodels_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertanyaandanjawabanmodels',
            name='penanya_obj',
        ),
        migrations.RemoveField(
            model_name='pertanyaandanjawabanmodels',
            name='penjawab_obj',
        ),
    ]
