# Generated by Django 4.1.2 on 2022-10-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0005_remove_pertanyaandanjawabanmodels_penanya_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaandanjawabanmodels',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pertanyaandanjawabanmodels',
            name='nama',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pertanyaandanjawabanmodels',
            name='no_hp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
