# Generated by Django 4.1.2 on 2022-10-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0007_pertanyaandanjawabanmodels_judul_pertanyaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaandanjawabanmodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pertanyaandanjawabanmodels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
