# Generated by Django 4.1.2 on 2022-10-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0008_pertanyaandanjawabanmodels_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pertanyaandanjawabanmodels',
            old_name='created_at',
            new_name='dibuat_pada',
        ),
        migrations.RenameField(
            model_name='pertanyaandanjawabanmodels',
            old_name='updated_at',
            new_name='dijawab_pada',
        ),
    ]
