# Generated by Django 4.1.2 on 2022-10-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0009_rename_created_at_pertanyaandanjawabanmodels_dibuat_pada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaandanjawabanmodels',
            name='jawaban',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pertanyaandanjawabanmodels',
            name='pertanyaan',
            field=models.TextField(blank=True),
        ),
    ]
