# Generated by Django 4.1.2 on 2022-11-04 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=10)),
                ('deskripsi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('awal_pendaftaran', models.DateField()),
                ('akhir_pendaftaran', models.DateField()),
                ('strata', models.CharField(choices=[('S2 - Strata 1', 'S2 - Strata 1'), ('S2 - Strata 2', 'S2 - Strata 2')], default='--Pilih Salah Satu--', max_length=255)),
                ('sistem_kuliah', models.CharField(choices=[('Reguler Pagi Kampus A', 'Reguler Pagi Kampus A'), ('Reguler Pagi Kampus B', 'Reguler Pagi Kampus B'), ('Reguler Sore Kampus A', 'Reguler Sore Kampus A'), ('Reguler Sore Kampus B', 'Reguler Sore Kampus B')], default='--Pilih Salah Satu--', max_length=255)),
                ('program_studi', models.CharField(choices=[('S1 - Ilmu Hukun (S1) ', 'S1 - Ilmu Hukun (S1) '), ('S2 - Ilmu Hukun (S2) ', 'S2 - Ilmu Hukun (S2) ')], default='--Pilih Salah Satu--', max_length=255)),
                ('gelombang', models.CharField(max_length=255)),
                ('formulir', models.CharField(default='BERBAYAR', max_length=20)),
                ('daya_tampung', models.BigIntegerField()),
                ('periode_pendaftaran', models.CharField(default='Periode Pendaftaran', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('ujian_hukum', models.CharField(default='Ujian Online Tes Wawasan Hukum', max_length=255)),
                ('ujian_kemampuan_dasar', models.CharField(default='Ujian Online Tes Kemampuan Dasar', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=100)),
                ('asal_sekolah', models.CharField(max_length=30)),
                ('tempat_lahir', models.CharField(max_length=35)),
                ('tanggal_lahir', models.DateField()),
                ('status', models.CharField(choices=[('Diterima', 'Diterima'), ('Pending', 'Pending'), ('Tidak Diterima', 'Tidak Diterima')], default='Pending', max_length=255)),
                ('angkatan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='admission.angkatan')),
                ('pengguna', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
