# Generated by Django 4.1.2 on 2022-10-15 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('deskripsi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=100)),
                ('asal_sekolah', models.CharField(max_length=30)),
                ('tempat_lahir', models.CharField(max_length=35)),
                ('tanggal_lahir', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('angkatan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='admission.angkatan')),
                ('pengguna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
