# Generated by Django 4.1.2 on 2022-11-04 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='jalur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Jalur+', to='admission.seleksi'),
        ),
        migrations.AddField(
            model_name='admission',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Program Studi+', to='admission.seleksi'),
        ),
    ]
