# Generated by Django 4.1.2 on 2022-10-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='booleean',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
