# Generated by Django 4.1.2 on 2022-11-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_admission_jalur_admission_program_studi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='jalur',
        ),
    ]
