# Generated by Django 4.1.2 on 2022-10-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_remove_admission_booleean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('Diterima', 'Diterima'), ('Pending', 'Pending'), ('Tidak Diterima', 'Tidak Diterima')], default='Pending', max_length=255),
        ),
    ]
