# Generated by Django 4.1.2 on 2022-11-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_seleksi_tanggal_mulai_ujian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleksi',
            name='strata',
            field=models.CharField(choices=[('S1 - Strata 1', 'S1 - Strata 1'), ('S2 - Strata 2', 'S2 - Strata 2')], default='--Pilih Salah Satu--', max_length=255),
        ),
    ]
