# Generated by Django 4.1.2 on 2022-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_admission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angkatan',
            name='tahun',
            field=models.CharField(max_length=4),
        ),
    ]
