# Generated by Django 4.1.2 on 2022-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_seleksi_strata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleksi',
            name='ujian_hukum',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seleksi',
            name='ujian_kemampuan_dasar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
