# Generated by Django 4.1.2 on 2022-10-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_angkatan_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='current_user',
            field=models.CharField(default='Masih Kosong', max_length=255),
        ),
    ]
