# Generated by Django 4.1.2 on 2022-10-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_admission_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='current_user',
            field=models.CharField(blank=True, default='Masih Kosong', max_length=255),
        ),
    ]
