# Generated by Django 4.1.2 on 2022-11-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_alter_seleksi_ujian_hukum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seleksi',
            name='tanggal_mulai_ujian',
        ),
        migrations.RemoveField(
            model_name='seleksi',
            name='tanggal_selesai_ujian',
        ),
        migrations.AddField(
            model_name='seleksi',
            name='tanggal_mulai_ujian_hukum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seleksi',
            name='tanggal_mulai_ujian_kemampuan_dasar',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seleksi',
            name='tanggal_selesai_ujian_hukum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seleksi',
            name='tanggal_selesai_ujian_kemampuan_dasar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
