# Generated by Django 4.1.2 on 2022-10-28 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0007_alter_admission_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='current_user',
        ),
        migrations.AlterField(
            model_name='admission',
            name='pengguna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
