# Generated by Django 4.1.2 on 2022-11-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_alter_seleksi_daya_tampung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleksi',
            name='daya_tampung',
            field=models.IntegerField(blank=True),
        ),
    ]
