# Generated by Django 4.1.2 on 2022-10-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('no_hp', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('user_msg', models.CharField(max_length=255)),
            ],
        ),
    ]
