# Generated by Django 4.1.2 on 2022-10-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='user_msg',
            field=models.TextField(),
        ),
    ]
