# Generated by Django 4.1.2 on 2022-10-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('slug', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('konten', models.TextField()),
                ('thumbnail', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT,
                 related_name='kategori', to='article.kategori')),
            ],
        ),
    ]
