# Generated by Django 4.1.2 on 2022-10-25 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='article_slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='article.kategori'),
        ),
    ]
