# Generated by Django 4.1.2 on 2022-10-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_artikel_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
