# Generated by Django 4.1.2 on 2022-10-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_kategori_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='article_slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
