# Generated by Django 4.1.2 on 2022-10-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_artikel_artikel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='kategori_content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
