# Generated by Django 4.1.2 on 2022-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_rename_kategori_content_artikel_kategori_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
