# Generated by Django 4.1.2 on 2022-10-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_artikel_kategori_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
