# Generated by Django 4.1.2 on 2022-10-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_kategori_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='artikel_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
