# Generated by Django 4.1.2 on 2022-10-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_alter_artikel_artikel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='artikel_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='kategori_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='kategori_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
