# Generated by Django 4.1.2 on 2022-10-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_alter_artikel_artikel_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='kategori',
        ),
    ]
